<?php

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property double $precio
 * @property integer $categoria_id
 * @property Doctrine_Collection $Plato
 * @property Doctrine_Collection $Semana
 * @property Doctrine_Collection $Itemsemana
 * @property Doctrine_Collection $Itemsmenu
 * @property Categoria $categoria
 * @property Itemsorden $itemsorden
 * 
 * @method double              getPrecio()       Returns the current record's "precio" value
 * @method integer             getCategoriaId()  Returns the current record's "categoria_id" value
 * @method Doctrine_Collection getPlato()        Returns the current record's "Plato" collection
 * @method Doctrine_Collection getSemana()       Returns the current record's "Semana" collection
 * @method Doctrine_Collection getItemsemana()   Returns the current record's "Itemsemana" collection
 * @method Doctrine_Collection getItemsmenu()    Returns the current record's "Itemsmenu" collection
 * @method Categoria           getCategoria()    Returns the current record's "categoria" value
 * @method Itemsorden          getItemsorden()   Returns the current record's "itemsorden" value
 * @method Menu                setPrecio()       Sets the current record's "precio" value
 * @method Menu                setCategoriaId()  Sets the current record's "categoria_id" value
 * @method Menu                setPlato()        Sets the current record's "Plato" collection
 * @method Menu                setSemana()       Sets the current record's "Semana" collection
 * @method Menu                setItemsemana()   Sets the current record's "Itemsemana" collection
 * @method Menu                setItemsmenu()    Sets the current record's "Itemsmenu" collection
 * @method Menu                setCategoria()    Sets the current record's "categoria" value
 * @method Menu                setItemsorden()   Sets the current record's "itemsorden" value
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('precio', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plato', array(
             'refClass' => 'ItemsMenu',
             'local' => 'menu_id',
             'foreign' => 'plato_id'));

        $this->hasMany('Semana', array(
             'refClass' => 'Itemsemana',
             'local' => 'menu_id',
             'foreign' => 'semana_id'));

        $this->hasMany('Itemsemana', array(
             'local' => 'id',
             'foreign' => 'menu_id'));

        $this->hasMany('Itemsmenu', array(
             'local' => 'id',
             'foreign' => 'menu_id'));

        $this->hasOne('Categoria as categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'id'));

        $this->hasOne('Itemsorden as itemsorden', array(
             'local' => 'id',
             'foreign' => 'menu_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}