<?php

/**
 * BaseSemana
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha_inicio
 * @property Doctrine_Collection $Menu
 * @property Doctrine_Collection $Itemsemana
 * 
 * @method date                getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method Doctrine_Collection getMenu()         Returns the current record's "Menu" collection
 * @method Doctrine_Collection getItemsemana()   Returns the current record's "Itemsemana" collection
 * @method Semana              setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method Semana              setMenu()         Sets the current record's "Menu" collection
 * @method Semana              setItemsemana()   Sets the current record's "Itemsemana" collection
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemana extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semana');
        $this->hasColumn('fecha_inicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Menu', array(
             'refClass' => 'Itemsemana',
             'local' => 'semana_id',
             'foreign' => 'menu_id'));

        $this->hasMany('Itemsemana', array(
             'local' => 'id',
             'foreign' => 'semana_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}