<?php

/**
 * BaseOrden
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $placedby_id
 * @property integer $direccion_id
 * @property double $monto
 * @property string $status
 * @property string $autorizacion
 * @property string $referencia
 * @property string $avsresultado
 * @property string $cvv2
 * @property string $mensajeerror
 * @property integer $cupon_id
 * @property boolean $manual
 * @property boolean $pago
 * @property Direccion $direccion
 * @property Doctrine_Collection $itemorden
 * @property Cupon $cupon
 * @property Usuario $Usuario
 * 
 * @method integer             getUsuarioId()    Returns the current record's "usuario_id" value
 * @method integer             getPlacedbyId()   Returns the current record's "placedby_id" value
 * @method integer             getDireccionId()  Returns the current record's "direccion_id" value
 * @method double              getMonto()        Returns the current record's "monto" value
 * @method string              getStatus()       Returns the current record's "status" value
 * @method string              getAutorizacion() Returns the current record's "autorizacion" value
 * @method string              getReferencia()   Returns the current record's "referencia" value
 * @method string              getAvsresultado() Returns the current record's "avsresultado" value
 * @method string              getCvv2()         Returns the current record's "cvv2" value
 * @method string              getMensajeerror() Returns the current record's "mensajeerror" value
 * @method integer             getCuponId()      Returns the current record's "cupon_id" value
 * @method boolean             getManual()       Returns the current record's "manual" value
 * @method boolean             getPago()         Returns the current record's "pago" value
 * @method Direccion           getDireccion()    Returns the current record's "direccion" value
 * @method Doctrine_Collection getItemorden()    Returns the current record's "itemorden" collection
 * @method Cupon               getCupon()        Returns the current record's "cupon" value
 * @method Usuario             getUsuario()      Returns the current record's "Usuario" value
 * @method Orden               setUsuarioId()    Sets the current record's "usuario_id" value
 * @method Orden               setPlacedbyId()   Sets the current record's "placedby_id" value
 * @method Orden               setDireccionId()  Sets the current record's "direccion_id" value
 * @method Orden               setMonto()        Sets the current record's "monto" value
 * @method Orden               setStatus()       Sets the current record's "status" value
 * @method Orden               setAutorizacion() Sets the current record's "autorizacion" value
 * @method Orden               setReferencia()   Sets the current record's "referencia" value
 * @method Orden               setAvsresultado() Sets the current record's "avsresultado" value
 * @method Orden               setCvv2()         Sets the current record's "cvv2" value
 * @method Orden               setMensajeerror() Sets the current record's "mensajeerror" value
 * @method Orden               setCuponId()      Sets the current record's "cupon_id" value
 * @method Orden               setManual()       Sets the current record's "manual" value
 * @method Orden               setPago()         Sets the current record's "pago" value
 * @method Orden               setDireccion()    Sets the current record's "direccion" value
 * @method Orden               setItemorden()    Sets the current record's "itemorden" collection
 * @method Orden               setCupon()        Sets the current record's "cupon" value
 * @method Orden               setUsuario()      Sets the current record's "Usuario" value
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrden extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orden');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('placedby_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('direccion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('monto', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('autorizacion', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'pendiente',
             'length' => 25,
             ));
        $this->hasColumn('referencia', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'pendiente',
             'length' => 30,
             ));
        $this->hasColumn('avsresultado', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('cvv2', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('mensajeerror', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
        $this->hasColumn('cupon_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('manual', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('pago', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Direccion as direccion', array(
             'local' => 'direccion_id',
             'foreign' => 'id'));

        $this->hasMany('Itemsorden as itemorden', array(
             'local' => 'id',
             'foreign' => 'orden_id'));

        $this->hasOne('Cupon as cupon', array(
             'local' => 'cupon_id',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}