<?php

/**
 * BaseTestimonio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property string $mensaje
 * @property Usuario $Usuario
 * 
 * @method integer    getUsuarioId()  Returns the current record's "usuario_id" value
 * @method string     getMensaje()    Returns the current record's "mensaje" value
 * @method Usuario    getUsuario()    Returns the current record's "Usuario" value
 * @method Testimonio setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Testimonio setMensaje()    Sets the current record's "mensaje" value
 * @method Testimonio setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestimonio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('testimonio');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mensaje', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}