<?php

/**
 * BaseItemsorden
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $orden_id
 * @property integer $menu_id
 * @property integer $plato_id
 * @property integer $cantidad
 * @property Menu $menu
 * @property Plato $plato
 * @property Orden $orden
 * 
 * @method integer    getOrdenId()  Returns the current record's "orden_id" value
 * @method integer    getMenuId()   Returns the current record's "menu_id" value
 * @method integer    getPlatoId()  Returns the current record's "plato_id" value
 * @method integer    getCantidad() Returns the current record's "cantidad" value
 * @method Menu       getMenu()     Returns the current record's "menu" value
 * @method Plato      getPlato()    Returns the current record's "plato" value
 * @method Orden      getOrden()    Returns the current record's "orden" value
 * @method Itemsorden setOrdenId()  Sets the current record's "orden_id" value
 * @method Itemsorden setMenuId()   Sets the current record's "menu_id" value
 * @method Itemsorden setPlatoId()  Sets the current record's "plato_id" value
 * @method Itemsorden setCantidad() Sets the current record's "cantidad" value
 * @method Itemsorden setMenu()     Sets the current record's "menu" value
 * @method Itemsorden setPlato()    Sets the current record's "plato" value
 * @method Itemsorden setOrden()    Sets the current record's "orden" value
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemsorden extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('itemsorden');
        $this->hasColumn('orden_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('menu_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('plato_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('cantidad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Menu as menu', array(
             'local' => 'menu_id',
             'foreign' => 'id'));

        $this->hasOne('Plato as plato', array(
             'local' => 'plato_id',
             'foreign' => 'id'));

        $this->hasOne('Orden as orden', array(
             'local' => 'orden_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}