<?php

/**
 * BaseTipoingrediente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ingrediente
 * @property Doctrine_Collection $Usuario
 * @property Doctrine_Collection $preferenciastipoingre
 * 
 * @method string              getName()                  Returns the current record's "name" value
 * @method Doctrine_Collection getIngrediente()           Returns the current record's "ingrediente" collection
 * @method Doctrine_Collection getUsuario()               Returns the current record's "Usuario" collection
 * @method Doctrine_Collection getPreferenciastipoingre() Returns the current record's "preferenciastipoingre" collection
 * @method Tipoingrediente     setName()                  Sets the current record's "name" value
 * @method Tipoingrediente     setIngrediente()           Sets the current record's "ingrediente" collection
 * @method Tipoingrediente     setUsuario()               Sets the current record's "Usuario" collection
 * @method Tipoingrediente     setPreferenciastipoingre() Sets the current record's "preferenciastipoingre" collection
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoingrediente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipoingrediente');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ingrediente as ingrediente', array(
             'local' => 'id',
             'foreign' => 'tipoingrediente_id'));

        $this->hasMany('Usuario', array(
             'refClass' => 'PreferenciasTipoingrediente',
             'local' => 'tipoingrediente_id',
             'foreign' => 'usuario_id'));

        $this->hasMany('Preferenciastipoingrediente as preferenciastipoingre', array(
             'local' => 'id',
             'foreign' => 'tipoingrediente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}