<?php

/**
 * BaseCupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property double $descuento
 * @property Orden $orden
 * 
 * @method string getName()      Returns the current record's "name" value
 * @method double getDescuento() Returns the current record's "descuento" value
 * @method Orden  getOrden()     Returns the current record's "orden" value
 * @method Cupon  setName()      Sets the current record's "name" value
 * @method Cupon  setDescuento() Sets the current record's "descuento" value
 * @method Cupon  setOrden()     Sets the current record's "orden" value
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cupon');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('descuento', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Orden as orden', array(
             'local' => 'id',
             'foreign' => 'cupon_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}