<?php

/**
 * BaseComoseentero
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $comoseentero
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getComoseentero() Returns the current record's "comoseentero" collection
 * @method Comoseentero        setName()         Sets the current record's "name" value
 * @method Comoseentero        setComoseentero() Sets the current record's "comoseentero" collection
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComoseentero extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comoseentero');
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario as comoseentero', array(
             'local' => 'id',
             'foreign' => 'comoseentero_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}