<?php

/**
 * BaseCreditcard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $numero
 * @property string $nombre
 * @property integer $codigo
 * @property string $fechavencimiento
 * @property integer $tipo
 * @property Usuario $Usuario
 * 
 * @method integer    getUsuarioId()        Returns the current record's "usuario_id" value
 * @method integer    getNumero()           Returns the current record's "numero" value
 * @method string     getNombre()           Returns the current record's "nombre" value
 * @method integer    getCodigo()           Returns the current record's "codigo" value
 * @method string     getFechavencimiento() Returns the current record's "fechavencimiento" value
 * @method integer    getTipo()             Returns the current record's "tipo" value
 * @method Usuario    getUsuario()          Returns the current record's "Usuario" value
 * @method Creditcard setUsuarioId()        Sets the current record's "usuario_id" value
 * @method Creditcard setNumero()           Sets the current record's "numero" value
 * @method Creditcard setNombre()           Sets the current record's "nombre" value
 * @method Creditcard setCodigo()           Sets the current record's "codigo" value
 * @method Creditcard setFechavencimiento() Sets the current record's "fechavencimiento" value
 * @method Creditcard setTipo()             Sets the current record's "tipo" value
 * @method Creditcard setUsuario()          Sets the current record's "Usuario" value
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Ing. Roberto Hernández De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCreditcard extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('creditcard');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('codigo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fechavencimiento', 'string', 7, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('tipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}