<?php

/**
 * ItemsordenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemsordenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemsordenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Itemsorden');
    }
}