<?php

/**
 * Itemsorden
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    fit2go
 * @subpackage model
 * @author     Roberto Hernandez De La Luz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Itemsorden extends BaseItemsorden
{

}