<?php

/**
 * OrdenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Orden');
    }
}