<?php

/**
 * PreferenciastipoingredienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreferenciastipoingredienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreferenciastipoingredienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preferenciastipoingrediente');
    }
}