<?php

/**
 * TipoingredienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoingredienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoingredienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipoingrediente');
    }
}